# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - '**.php'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
#  psalm:
#    name: Psalm
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Psalm Security Scan
#        uses: docker://ghcr.io/psalm/psalm-security-scan
#
#      - name: Upload Security Analysis results to GitHub
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: results.sarif
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: appleboy/ssh-action@master
        with:
          host: '217.182.241.177'
          username: 'modgen'
          password: 'cQ_3JCcbzNzwV'
          port: 2222
          script: |
            cd ..
            cd ..
            cd web/
            git checkout -- .
            git pull origin master
            git status